name: Todo App CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: |
          npm run test:coverage
          cp coverage/lcov-report/lcov.info coverage/lcov.info || echo "Missing coverage file"
      - uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          flags: backend
          fail_ci_if_error: false
      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-${{ matrix.node-version }}
          path: coverage/

  e2e-tests:
    needs: api-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
      - name: Backend Startup
        run: |
          npm start &
          npx wait-on http://localhost:5000/api/health --timeout 60000
      - name: Frontend Startup
        run: |
          cd frontend && npm start &
          npx wait-on http://localhost:3000 --timeout 60000
      - uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:3000,http://localhost:5000/api/health
          wait-on-timeout: 60
          config: baseUrl=http://localhost:3000
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npx eslint . --ext .js,.jsx || true
      - uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm audit --audit-level=high || true
      - uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'

env:
  CI: true
  NODE_ENV: test
